server:
    port: 10000
    servlet:
        context-path: /Shopme
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password:
        url: jdbc:mysql://localhost:3337/shopmedb
        username:
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
        show-sql: true
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 190949295583-pgib1pu9l36b71aqa2pnc9iglael9ell.apps.googleusercontent.com
                        client-secret: cNcvlHmvEM-291fJuyF0lp0D
                        scope:
                        - email
                        - profile
                    facebook:
                        client-id: 1377246809343324
                        client-secret: 8adea8b221ba7c675703c9f02c1babc9
                        scope:
                            - email
                            - public_profile
    thymeleaf:
        cache: false
