server:
    port: 10000
    servlet:
        context-path: /Shopme
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: m.YsqlCLAU1214
        url: jdbc:mysql://localhost:3306/shopmedb
        username: placidmasvidal
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
        show-sql: true
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 190949295583-pgib1pu9l36b71aqa2pnc9iglael9ell.apps.googleusercontent.com
                        client-secret: cNcvlHmvEM-291fJuyF0lp0D
                        scope:
                        - email
                        - profile
    thymeleaf:
        cache: false
